"""
Intent taxonomy, development labeling rules, text normalization, and dataset extraction
for AmazonHelp customer support conversations.

NOTE ON LABELING METHODOLOGY:
Labels generated by this module are deterministic, rule-based WEAK/DEVELOPMENT LABELS
designed strictly to establish baseline feasibility, debug modeling pipelines, and
perform error analysis prior to human annotation. They MUST NOT be confused with or
reported as human gold-standard ground truth.

PRODUCTION CLASSIFIER (Candidate D — Hybrid):
The ``HybridIntentClassifier`` class implements the production-selected Candidate D
architecture: a high-precision deterministic regex cascade (confidence ≥ 0.85) that
triage unambiguous intents, backed by a Balanced LinearSVC trained on Word+Char TF-IDF
features (50k-feature FeatureUnion) for the remaining cases.  It is evaluated once on
the frozen 200-example Human Golden Set: 57.00% accuracy / 0.5971 Macro-F1, an
absolute +18.50 pp / +0.1937 Macro-F1 improvement over the TF-IDF+LR baseline.
"""

from dataclasses import dataclass, field
import json
from pathlib import Path
import re
from typing import Any, Dict, List, Optional, Tuple


@dataclass(frozen=True)
class IntentDefinition:
    """Specification of a customer support intent."""
    name: str
    display_name: str
    department: str
    description: str
    inclusion_criteria: str
    exclusion_criteria: str
    likely_confusions: List[str]
    representative_examples: List[str]


# ------------------------------------------------------------------------------
# Final Candidate Intent Taxonomy (10 mutually distinguishable intents)
# ------------------------------------------------------------------------------

INTENT_TAXONOMY: Dict[str, IntentDefinition] = {
    "delivery_status_tracking": IntentDefinition(
        name="delivery_status_tracking",
        display_name="Delivery Status & Tracking",
        department="Logistics & Transportation (AMZL / Carriers)",
        description=(
            "Customer inquiring about the whereabouts, dispatch status, estimated arrival date/time, "
            "courier transit issues, carrier delays, or tracking updates of an order."
        ),
        inclusion_criteria=(
            "Mentions of shipping, dispatch, tracking number, courier/carrier (AMZL, UPS, Hermes, etc.), "
            "delivery delays, package not arrived, ETA inquiries, or out-for-delivery status."
        ),
        exclusion_criteria=(
            "Reports of physically damaged, broken, or empty boxes (classified as damaged_defective_wrong_item). "
            "Requests to cancel an in-transit order (classified as order_cancellation_modification)."
        ),
        likely_confusions=[
            "damaged_defective_wrong_item (when customer mentions 'package arrived broken')",
            "order_cancellation_modification (when customer wants to cancel because of a delay)",
            "return_refund_exchange (when customer asks for refund due to late delivery)",
        ],
        representative_examples=[
            "why is my order at my local courier for the last 6 days and still hasn’t been delivered to me??",
            "Item has not been delivered but tracking says it was handed to me over an hour ago...",
            "What's with the shipping? I order something on Saturday, and it's not arriving until Wednesday?",
            "発送された商品の追跡番号を教えてください。",
            "Mon colis devait arriver aujourd'hui mais je n'ai toujours rien reçu.",
        ],
    ),
    "return_refund_exchange": IntentDefinition(
        name="return_refund_exchange",
        display_name="Returns, Refunds & Exchanges",
        department="Returns & Reverse Logistics",
        description=(
            "Customer requesting to return an eligible item, check refund processing status, "
            "obtain a prepaid return label, or request an exchange/reimbursement."
        ),
        inclusion_criteria=(
            "Explicit requests for return labels, refund status, money back, returning goods, "
            "product exchange, or reimbursement for return shipping costs."
        ),
        exclusion_criteria=(
            "First-time reports of defective/damaged items without explicit return/refund request "
            "(classified as damaged_defective_wrong_item). Payment gateway errors or unexpected bank charges "
            "(classified as payment_billing_promotions)."
        ),
        likely_confusions=[
            "damaged_defective_wrong_item (when customer says 'it arrived broken, I want a refund')",
            "payment_billing_promotions (when customer asks where their refund credit is)",
        ],
        representative_examples=[
            "I called customer service and was told my membership wouldn't be renewed. How do I get a refund?",
            "Can I get a return shipping label? The item is still unopened.",
            "I dropped off my return package at Hermes 5 days ago, when will my refund be issued?",
            "返品の仕方を教えてください。返金はいつ頃になりますか？",
            "Je souhaite retourner cet article et être remboursé au plus vite.",
        ],
    ),
    "damaged_defective_wrong_item": IntentDefinition(
        name="damaged_defective_wrong_item",
        display_name="Damaged, Defective or Wrong Item",
        department="Product Quality & Replacement",
        description=(
            "Customer reporting that an item arrived broken, scratched, defective, non-functional, "
            "missing parts, inside an empty/opened box, or completely different from what was ordered."
        ),
        inclusion_criteria=(
            "Physical damage, defective electronics, missing pieces, shattered/scratched goods, "
            "fake/counterfeit goods, or wrong item/variant received."
        ),
        exclusion_criteria=(
            "Late deliveries where the package is intact (classified as delivery_status_tracking). "
            "Digital content playback errors (classified as prime_digital_services)."
        ),
        likely_confusions=[
            "delivery_status_tracking (when package is damaged by the courier in transit)",
            "return_refund_exchange (when customer explicitly demands return rather than describing defect)",
        ],
        representative_examples=[
            "my package was ‘accidentally’ opened.. 4 items missing worth £97. You need better delivery drivers!!",
            "The screen on the monitor I received is cracked and shattered completely.",
            "I ordered size 10 shoes and you sent me size 7. This is the wrong product.",
            "届いた商品の箱が潰れていて中身が破損していました。交換できますか？",
            "Ihr Flaschen! Erst habt ihr mir ein Paket mit falschem Inhalt geschickt...",
        ],
    ),
    "order_cancellation_modification": IntentDefinition(
        name="order_cancellation_modification",
        display_name="Order Cancellation & Modification",
        department="Order Management & Fulfillment",
        description=(
            "Customer seeking to cancel an existing order, stop an accidental purchase, or modify "
            "order details such as shipping address or payment method before dispatch."
        ),
        inclusion_criteria=(
            "Phrases like cancel my order, stop order, change delivery address, cancel accidentally placed order, "
            "or cancel subscription order."
        ),
        exclusion_criteria=(
            "Canceling an account or deleting user profile (classified as account_access_security). "
            "Canceling a Prime subscription (classified as prime_digital_services)."
        ),
        likely_confusions=[
            "prime_digital_services (when canceling Prime membership specifically)",
            "delivery_status_tracking (when canceling because delivery is taking too long)",
        ],
        representative_examples=[
            "Please cancel order # 123-4567890-1234567 I bought it by accident.",
            "Can I change the delivery address for my order? It hasn't shipped yet.",
            "I tried to cancel my order online but the button is greyed out. Help please!",
            "注文をキャンセルしたいのですが、まだ間に合いますか？",
            "Pouvez-vous annuler ma commande passée ce matin par erreur ?",
        ],
    ),
    "payment_billing_promotions": IntentDefinition(
        name="payment_billing_promotions",
        display_name="Payment, Billing & Promotions",
        department="Billing & Payments Support",
        description=(
            "Customer experiencing payment transaction errors, unexpected or duplicate charges, "
            "gift card balance or redemption issues, promo code failures, or invoice requests."
        ),
        inclusion_criteria=(
            "Mentions of credit/debit cards, bank deductions, unauthorized charges, double billing, "
            "gift cards, vouchers, promo/discount codes, invoices, or payment gateway failures."
        ),
        exclusion_criteria=(
            "Recurring Prime subscription membership fees (classified as prime_digital_services unless "
            "purely disputing an unrecognized charge). Pure refund requests for returned items (return_refund_exchange)."
        ),
        likely_confusions=[
            "prime_digital_services (when customer complains about Prime renewal fee)",
            "return_refund_exchange (when customer asks where their refund credit is)",
        ],
        representative_examples=[
            "where can I chat with a support member for a false charge?",
            "when do you guys charge for the Xbox one X I preordered? It ships the 6th.",
            "My gift card code says it is already redeemed, but my balance is still zero.",
            "promotion code doesn’t work on checkout",
            "Amazonさんから支払い番号がこないんだが…",
        ],
    ),
    "prime_digital_services": IntentDefinition(
        name="prime_digital_services",
        display_name="Prime & Digital Services",
        department="Digital Devices & Subscriptions (Prime, Kindle, Fire TV, Echo/Alexa)",
        description=(
            "Customer having questions or technical issues with Amazon Prime benefits, Prime Video streaming, "
            "Kindle e-readers/ebooks, Fire TV hardware/apps, Echo/Alexa devices, or Amazon Music."
        ),
        inclusion_criteria=(
            "Prime Video playback/buffering errors, Fire TV app crashes, Kindle syncing/page numbers, "
            "Alexa voice commands, Prime membership benefits questions, or Amazon Music subscriptions."
        ),
        exclusion_criteria=(
            "General retail order deliveries even if placed with Prime shipping (classified as delivery_status_tracking). "
            "Physical damage to retail items (classified as damaged_defective_wrong_item)."
        ),
        likely_confusions=[
            "delivery_status_tracking (when customer complains Prime 2-day delivery was slow)",
            "payment_billing_promotions (when customer asks about Prime membership price)",
        ],
        representative_examples=[
            "also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?",
            "I'm watching SUITS on firetv. Whenever I play SUITS, it always go to SE03EP01 by default",
            "you need to notify new users that the page numbers do not match up with the paper copies on Kindle.",
            "amazonのfireTVstickが見れない😢",
            "amazonプライムビデオ、再生エラーが多いです",
        ],
    ),
    "account_access_security": IntentDefinition(
        name="account_access_security",
        display_name="Account Access & Security",
        department="Customer Trust, Identity & Account Security",
        description=(
            "Customer unable to log into their account, locked out, encountering OTP/2FA errors, "
            "suspecting account compromise or hacking, or requesting account closure."
        ),
        inclusion_criteria=(
            "Password reset failures, OTP not received, 2FA issues, suspended or blocked accounts, "
            "unauthorized account activity / hacked reports, or closing/deleting account."
        ),
        exclusion_criteria=(
            "Credit card fraud reports without account compromise (payment_billing_promotions). "
            "Simple address book changes within an active account (order_cancellation_modification)."
        ),
        likely_confusions=[
            "payment_billing_promotions (when customer suspects a charge was made by a hacker)",
            "feedback_complaint_chatter (when customer vents about being blocked without giving details)",
        ],
        representative_examples=[
            "I want my amazon payments account CLOSED. dm me please.",
            "Bought an Echo Show and it won’t recognize a single account in our household.",
            "Why would Amazon hack my account? Some employee must have been in there hacking people.",
            "Bonjour, mon compte Amazon est bloque suite a une commande, toujours rien après 24h.",
            "パスワードを再設定しようとしても確認メールが届きません。",
        ],
    ),
    "product_seller_inquiry": IntentDefinition(
        name="product_seller_inquiry",
        display_name="Product & Seller Inquiry",
        department="Retail & Marketplace Operations",
        description=(
            "Customer or merchant asking about product availability/stock, specifications, warranty, "
            "third-party seller policies, price matching, or selling items on Amazon."
        ),
        inclusion_criteria=(
            "Stock restock dates, product compatibility, seller authenticity/marketplace questions, "
            "how to sell on Amazon, or general pre-purchase questions."
        ),
        exclusion_criteria=(
            "Post-purchase damaged goods (damaged_defective_wrong_item). Inquiries about orders already placed "
            "(delivery_status_tracking or return_refund_exchange)."
        ),
        likely_confusions=[
            "damaged_defective_wrong_item (when inquiring about counterfeit vs receiving counterfeit)",
            "other_unclear (when question is extremely generic like 'how do I buy?')",
        ],
        representative_examples=[
            "I want to sell globally on Amazon. Where do I register as a seller?",
            "When will the Nintendo Switch be back in stock on Amazon?",
            "Are items sold by third-party sellers covered by the A-to-Z guarantee?",
            "Amazonとかで物買ったことある人いますか？いたら買い方教えてほしいです",
            "Ce produit est-il compatible avec les ordinateurs sous Windows 10 ?",
        ],
    ),
    "feedback_complaint_chatter": IntentDefinition(
        name="feedback_complaint_chatter",
        display_name="Feedback, Complaints & Social Chatter",
        department="Social Media Engagement & Executive Relations",
        description=(
            "Customer expressing generic brand sentiment, dissatisfaction, compliments, gratitude, "
            "social media banter (e.g. pets playing in Amazon boxes), promotional quiz contests, or broad feedback."
        ),
        inclusion_criteria=(
            "Generic rants ('worst customer service ever!'), praise ('thank you for your help!'), "
            "social memes, box photos, app quiz inquiries (#AmazonAppQuiz), or general opinions without transactional issue."
        ),
        exclusion_criteria=(
            "Actionable reports with order numbers, tracking issues, or refund requests (routed to respective operational intent). "
            "Empty or uninterpretable single-word noise (classified as other_unclear)."
        ),
        likely_confusions=[
            "other_unclear (distinction between generic sentiment vs complete lack of context)",
            "account_access_security (when venting about account block without account details)",
        ],
        representative_examples=[
            "thank you for your help. Got my thing done within a day. really appreciate it 👍",
            "AMAZON IS THE WORST COMPANY EVER, UNTRAINED AGENTS AND USELESS CHATBOTS!",
            "Au lieu de jeter un carton il vaut mieux adopter un ou deux chats ! C’est bien plus utile !",
            "#OnePlus5TAppQuiz @AmazonHelp where is a OnePlus5t winner list",
            "Geil!!! xD Danke womit habe ich diese Ehre verdient? 😂",
        ],
    ),
    "other_unclear": IntentDefinition(
        name="other_unclear",
        display_name="Other / Unclear / Context-Dependent",
        department="Front-Line Triage",
        description=(
            "Inbound messages that lack sufficient information to determine intent without further context, "
            "such as greetings, isolated follow-up fragments ('yes', 'DM sent', '__email__'), or uninterpretable noise."
        ),
        inclusion_criteria=(
            "Isolated greetings ('hi', 'need help'), isolated email addresses or phone numbers, "
            "fragmented replies in multi-turn threads, or unclassifiable queries."
        ),
        exclusion_criteria=(
            "Any query containing unambiguous keywords matching the 9 operational intents above."
        ),
        likely_confusions=[
            "feedback_complaint_chatter (when message is a vague complaint vs purely unclear)",
        ],
        representative_examples=[
            "hi I need Help",
            "__email__",
            "Yes, I already replied to your DM.",
            "Please check",
            "ok",
        ],
    ),
}

INTENT_NAMES: List[str] = [
    "delivery_status_tracking",
    "return_refund_exchange",
    "damaged_defective_wrong_item",
    "order_cancellation_modification",
    "payment_billing_promotions",
    "prime_digital_services",
    "account_access_security",
    "product_seller_inquiry",
    "feedback_complaint_chatter",
    "other_unclear",
]


# ------------------------------------------------------------------------------
# Normalization
# ------------------------------------------------------------------------------

LABEL_ALIASES: Dict[str, str] = {
    "delivery": "delivery_status_tracking",
    "delivery_delay_status": "delivery_status_tracking",
    "tracking": "delivery_status_tracking",
    "shipping": "delivery_status_tracking",
    "returns": "return_refund_exchange",
    "refund": "return_refund_exchange",
    "return_refund": "return_refund_exchange",
    "damage": "damaged_defective_wrong_item",
    "defective": "damaged_defective_wrong_item",
    "damaged_defective": "damaged_defective_wrong_item",
    "cancel": "order_cancellation_modification",
    "cancellation": "order_cancellation_modification",
    "order_cancellation": "order_cancellation_modification",
    "payment": "payment_billing_promotions",
    "billing": "payment_billing_promotions",
    "payment_billing_giftcard": "payment_billing_promotions",
    "prime": "prime_digital_services",
    "digital": "prime_digital_services",
    "account": "account_access_security",
    "security": "account_access_security",
    "product": "product_seller_inquiry",
    "seller": "product_seller_inquiry",
    "feedback": "feedback_complaint_chatter",
    "complaint": "feedback_complaint_chatter",
    "chatter": "feedback_complaint_chatter",
    "general_inquiry_other": "other_unclear",
    "other": "other_unclear",
    "unclear": "other_unclear",
}


def normalize_intent_label(label: str) -> str:
    """Normalize any alias or legacy label into the canonical taxonomy name."""
    clean = label.strip().lower()
    if clean in INTENT_TAXONOMY:
        return clean
    if clean in LABEL_ALIASES:
        return LABEL_ALIASES[clean]
    raise ValueError(f"Unknown intent label '{label}'. Must be one of: {INTENT_NAMES}")


# ------------------------------------------------------------------------------
# Text Preprocessing & Cleaning
# ------------------------------------------------------------------------------

def clean_tweet_text(text: str) -> str:
    """
    Standard NLP cleaner for Twitter support text.
    Removes handles (@username, @12345) and URLs to prevent overfitting to specific IDs,
    while preserving actual natural language tokens, punctuation, and casing.
    """
    # Remove URLs
    text = re.sub(r"https?://\S+", " ", text)
    # Remove user mentions
    text = re.sub(r"@\w+", " ", text)
    # Collapse multiple whitespace
    text = re.sub(r"\s+", " ", text).strip()
    return text


# ------------------------------------------------------------------------------
# Deterministic Weak / Development Labeling Engine
# ------------------------------------------------------------------------------

# Compiled multilingual regex rules
INTENT_PATTERNS: Dict[str, re.Pattern] = {
    "damaged_defective_wrong_item": re.compile(
        r"(\b(damage|damaged|damages|broken|defective|faulty|wrong (item|product|order|size|color)|"
        r"missing (item|part|package|items|content)|empty box|scratched|shattered|torn|smashed|"
        r"dented|fake|counterfeit|poor quality|opened box|wrong picked)\b|"
        r"破損|壊れ|不良品|違う商品|欠品|"
        r"beschädigt|defekt|falscher artikel|falschem inhalt|"
        r"endommagé|défectueux|dañado|roto|artículo incorrecto|danneggiato|difettoso)",
        re.IGNORECASE
    ),
    "order_cancellation_modification": re.compile(
        r"(\b(cancel|canceling|cancelling|cancellation|cancelled|canceled|"
        r"change order|modify order|wrong address|change address|change shipping address|"
        r"cancel my order|cancel order)\b|"
        r"キャンセル|stornieren|stornierung|annuler|annulation|cancelar|cancelación|annulla|annullare)",
        re.IGNORECASE
    ),
    "return_refund_exchange": re.compile(
        r"(\b(return|returning|returned|returns|refund|refunded|refunding|refunds|"
        r"exchange|exchanged|exchanging|money back|reimburse|reimbursement|return label|send back)\b|"
        r"返品|返金|交換|rücksendung|erstatten|erstattung|retour|remboursement|devolución|reembolso|reso|rimborso)",
        re.IGNORECASE
    ),
    "payment_billing_promotions": re.compile(
        r"(\b(charged|charge|charges|payment|paying|paid|billing|invoice|receipt|"
        r"credit card|debit card|bank account|transaction|wallet|gift card|giftcard|"
        r"voucher|promo code|promotion code|promotional code|coupon|overcharged|"
        r"double charge|unauthorized charge|deducted|balance|discount)\b|"
        r"支払い|請求|ギフト券|クレカ|"
        r"bezahlung|rechnung|gutschein|paiement|facture|chèque-cadeau|pago|factura|"
        r"tarjeta de regalo|pagamento|fattura|buono regalo)",
        re.IGNORECASE
    ),
    "account_access_security": re.compile(
        r"(\b(login|log in|logging in|sign in|signing in|password|passcode|otp|"
        r"verification code|two.factor|2fa|hacked|hack|locked account|account locked|"
        r"suspended account|close my account|delete account|compromised|reset password)\b|"
        r"ログイン|パスワード|アカウント停止|"
        r"konto|passwort|anmeldung|connexion|mot de passe|cuenta|contraseña|accesso|compte.*bloqu)",
        re.IGNORECASE
    ),
    "delivery_status_tracking": re.compile(
        r"(\b(delivery|deliver|delivering|delivered|delivers|shipping|shipped|shipment|"
        r"courier|carrier|track|tracking|dispatch|dispatched|eta|transit|arrived|arrival|"
        r"late|delayed|delay|haven\'t received|hasn\'t arrived|not received|still waiting|"
        r"where is my (order|package|item|parcel)|out for delivery|undelivered|package|parcel)\b|"
        r"\b(order|orders)\b.*?\b(arrive|reach|come|received|status|when|where|today|tomorrow|yesterday|date)\b|"
        r"発送|届かない|届きません|配達|配送|追跡|未着|届く|"
        r"lieferung|versand|zugestellt|livraison|livré|expédié|colis|entrega|enviado|spedizione|consegna|paquete|pacchetto)",
        re.IGNORECASE
    ),
    "prime_digital_services": re.compile(
        r"(\b(prime video|prime music|kindle|ebook|audiobook|fire ?tv|fire ?stick|alexa|echo|"
        r"audible|stream|streaming|prime membership|prime member|renew membership|annual fee|pilot series)\b|"
        r"プライム|キンドル|エコー|アレクサ|prime video|abo prime|abbonamento prime)",
        re.IGNORECASE
    ),
    "product_seller_inquiry": re.compile(
        r"(\b(seller|merchant|in stock|out of stock|restock|availability|warranty|"
        r"price match|specs|specification|compatibility|genuine|authentic|how to buy|"
        r"sell on amazon|sell globally|third.party seller|marketplace)\b|"
        r"在庫|販売者|出品|買い方|verkäufer|lagernd|vendeur|en stock|vendedor|venditore|disponibile)",
        re.IGNORECASE
    ),
    "feedback_complaint_chatter": re.compile(
        r"(\b(worst|horrible|terrible|scam|cheat|pathetic|disappointed|not happy|racism|"
        r"app|website|site|bug|crash|customer service|agent|rude|complaint|thank you|thanks|"
        r"love amazon|quiz|winner)\b|"
        r"danke|merci|grazie|obrigado|gracias|ありがとう)",
        re.IGNORECASE
    ),
}

# Priority ordering for disambiguation when multiple intents match:
# 1. Damage & Defect is most urgent and specific.
# 2. Cancellation is highly time-sensitive.
# 3. Return & Refund takes priority over generic delivery/billing.
# 4. Payment & Billing precedes delivery.
# 5. Account Security is critical.
# 6. Delivery Tracking is high volume and operational.
# 7. Prime & Digital Services.
# 8. Product & Seller inquiries.
# 9. Generic Feedback / Chatter.
PRIORITY_ORDER: List[str] = [
    "damaged_defective_wrong_item",
    "order_cancellation_modification",
    "return_refund_exchange",
    "payment_billing_promotions",
    "account_access_security",
    "delivery_status_tracking",
    "prime_digital_services",
    "product_seller_inquiry",
    "feedback_complaint_chatter",
]


def classify_message_intent(text: str) -> Tuple[str, float, str]:
    """
    Classify a customer message using deterministic priority regex rules.
    Returns: (intent_name, confidence, labeling_method)

    - Confidence is 0.85 for unambiguous single/priority rule matches.
    - Confidence is 0.30 for unmatched fallback ('other_unclear').
    """
    for intent in PRIORITY_ORDER:
        pat = INTENT_PATTERNS[intent]
        if pat.search(text):
            return intent, 0.85, f"regex_rule_{intent}"

    return "other_unclear", 0.30, "fallback_unmatched"


# ------------------------------------------------------------------------------
# Production Classifier: Candidate D — Hybrid (Regex Cascade + ML Fallback)
# ------------------------------------------------------------------------------

_DEFAULT_TRAIN_FILE = (
    Path(__file__).resolve().parent.parent
    / "data/processed/amazonhelp_dev_train.jsonl"
)


class HybridIntentClassifier:
    """
    Production intent classifier — Candidate D (selected by Validation Macro-F1).

    Architecture
    ------------
    1. **Regex cascade** (confidence ≥ 0.85): deterministic, zero-latency triage for
       the 9 operational intents using ``classify_message_intent``.
    2. **ML fallback**: Balanced ``LinearSVC`` (C=0.5, dual=False) trained on a
       50,000-feature ``FeatureUnion`` of Word TF-IDF n-grams (1-2) and character
       subword n-grams (3-5) for examples not captured with high confidence by the
       regex stage.

    Training Data
    -------------
    Strictly ``data/processed/amazonhelp_dev_train.jsonl`` (57,760 weak-label
    examples).  The 200-example frozen Human Golden Set is *never* used for training.

    Performance on Frozen 200-Example Human Golden Set
    --------------------------------------------------
    * Accuracy:   57.00%   (+18.50 pp vs. TF-IDF+LR baseline of 38.50%)
    * Macro-F1:    0.5971  (+0.1937 vs. baseline of 0.4034)
    * Weighted-F1: 0.5915

    Usage
    -----
    >>> clf = HybridIntentClassifier()   # trains lazily on first call or at init
    >>> intent, conf, method = clf.classify("Where is my order?")
    """

    def __init__(
        self,
        train_file: Optional[Path] = None,
        regex_confidence_threshold: float = 0.85,
    ) -> None:
        self._train_file = Path(train_file) if train_file else _DEFAULT_TRAIN_FILE
        self._threshold = regex_confidence_threshold
        self._vectorizer = None  # FeatureUnion, fitted lazily
        self._clf = None         # LinearSVC, fitted lazily
        self._is_trained = False

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def classify(self, text: str) -> Tuple[str, float, str]:
        """
        Classify a customer message using the Candidate D hybrid architecture.

        Parameters
        ----------
        text:
            Raw customer tweet text (handles and URLs will be stripped internally).

        Returns
        -------
        (intent_name, confidence, method)
            * ``intent_name`` — one of the 10 canonical intent labels.
            * ``confidence``  — 0.85 for regex hits, 0.75 for ML predictions,
              0.30 for unmatched fallback.
            * ``method``      — provenance tag: ``"regex_rule_<intent>"``,
              ``"hybrid_ml_svc"``, or ``"hybrid_fallback_unmatched"``.
        """
        # Stage 1: high-precision regex cascade
        rule_intent, rule_conf, rule_method = classify_message_intent(text)
        if rule_conf >= self._threshold and rule_intent != "other_unclear":
            return rule_intent, rule_conf, rule_method

        # Stage 2: ML fallback — train on demand if needed
        if not self._is_trained:
            self._train()

        if self._clf is None:
            # Training data unavailable — degrade gracefully to regex result
            return rule_intent, rule_conf, rule_method

        cleaned = clean_tweet_text(text)
        X = self._vectorizer.transform([cleaned])
        pred = self._clf.predict(X)[0]

        if pred == "other_unclear":
            return pred, 0.30, "hybrid_fallback_unmatched"
        return pred, 0.75, "hybrid_ml_svc"

    @property
    def is_trained(self) -> bool:
        """True if the ML fallback model has been fitted."""
        return self._is_trained

    def train(self, train_file: Optional[Path] = None) -> "HybridIntentClassifier":
        """Explicitly train the ML fallback.  Returns self for chaining."""
        self._train(train_file=train_file)
        return self

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _train(self, train_file: Optional[Path] = None) -> None:
        """Fit the Word+Char FeatureUnion and LinearSVC on the dev-train file."""
        path = Path(train_file) if train_file else self._train_file
        if not path.exists():
            # Graceful degradation: mark as trained (no-op ML stage)
            self._is_trained = True
            return

        try:
            from sklearn.feature_extraction.text import TfidfVectorizer
            from sklearn.pipeline import FeatureUnion
            from sklearn.svm import LinearSVC
        except ImportError as exc:  # pragma: no cover
            raise ImportError(
                "scikit-learn is required for HybridIntentClassifier. "
                "Install it with: pip install scikit-learn"
            ) from exc

        records: List[Dict[str, Any]] = []
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    records.append(json.loads(line))

        train_texts = [r.get("cleaned_text") or clean_tweet_text(r.get("customer_message", "")) for r in records]
        train_labels = [r["intent"] for r in records]

        vectorizer = FeatureUnion([
            ("word", TfidfVectorizer(
                ngram_range=(1, 2), min_df=2, max_features=25000, sublinear_tf=True
            )),
            ("char", TfidfVectorizer(
                ngram_range=(3, 5), analyzer="char_wb", min_df=5,
                max_features=25000, sublinear_tf=True,
            )),
        ])
        X_train = vectorizer.fit_transform(train_texts)

        clf = LinearSVC(C=0.5, class_weight="balanced", dual=False, random_state=42, max_iter=2000)
        clf.fit(X_train, train_labels)

        self._vectorizer = vectorizer
        self._clf = clf
        self._is_trained = True


# ------------------------------------------------------------------------------
# Dataset Extraction & Preparation
# ------------------------------------------------------------------------------

def build_dev_record(
    conversation: Dict[str, Any],
    interaction_pair: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Construct a single labeled development dataset example from an interaction pair.
    Preserves conversational context for future context-ablation experiments.
    """
    cust_text = interaction_pair["customer_text"]
    cleaned = clean_tweet_text(cust_text)
    intent, conf, method = classify_message_intent(cust_text)

    return {
        "conversation_id": conversation["conversation_id"],
        "root_id": conversation["root_id"],
        "turn_index": interaction_pair["turn_index"],
        "customer_tweet_id": interaction_pair["customer_tweet_id"],
        "customer_author_id": interaction_pair["customer_author_id"],
        "customer_message": cust_text,
        "cleaned_text": cleaned,
        "support_tweet_id": interaction_pair["support_tweet_id"],
        "support_response": interaction_pair["support_text"],
        "prior_context": interaction_pair.get("prior_context", []),
        "intent": intent,
        "confidence": conf,
        "labeling_method": method,
    }


def extract_dev_dataset_from_conversations(
    conversations: List[Dict[str, Any]],
    turn1_only: bool = False,
) -> List[Dict[str, Any]]:
    """
    Extract development examples from a list of conversation objects.
    If turn1_only is True, extracts only the opening customer inquiry (turn_index == 1).
    Otherwise extracts all direct interaction pairs while recording turn_index.
    """
    records = []
    for conv in conversations:
        for pair in conv.get("interaction_pairs", []):
            if turn1_only and pair["turn_index"] != 1:
                continue
            record = build_dev_record(conv, pair)
            records.append(record)
    return records
